# Telegram Bot Token (??? ????? ?? BotFather)
telegram.bot.token=8271615199:AAGRrrCB-nv4DXfpcK4F4yBGkZMXdDw-Zm4

spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot_db2
spring.datasource.username=telegram_user
spring.datasource.password=Dinozavr2007

spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/v-1.0/changelog-master.xml